filter:
    paths: ["src/*"]
tools:
    php_sim: true
    php_pdepend: false
    php_analyzer: true
    php_cpd: false
    php_mess_detector:
        enabled: false
    php_code_sniffer:
        enabled: false
