<?php
/**
 * Core file loader
 *
 * @package BEAR.Framework
 * @license http://opensource.org/licenses/bsd-license.php BSD
 *
 * @global  $system system path
 */
namespace BEAR\Framework\Scripts;

use BEAR\Framework\Framework\Framework;

if (isset($system)) {
    return;
}

$system = Framework::$systemRoot;
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Annotations/AnnotationRegistry.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/AbstractModule.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/Scope.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Annotations/Reader.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Annotations/AnnotationReader.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Annotations/DocParser.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Lexer.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Annotations/DocLexer.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Annotations/Annotation/Target.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Annotations/PhpParser.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Matchable.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Matcher.php';
include $system . '/src/BEAR/Framework/Module/FrameworkModule.php';
include $system . '/src/BEAR/Framework/Module/Log/MonologModule.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/ProviderInterface.php';
include $system . '/src/BEAR/Framework/Module/Log/MonologModule/MonologProvider.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/InjectorInterface.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/Injector.php';
include $system . '/vendor/aura/di/src/Aura/Di/ContainerInterface.php';
include $system . '/vendor/aura/di/src/Aura/Di/Container.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/Container.php';
include $system . '/vendor/aura/di/src/Aura/Di/ForgeInterface.php';
include $system . '/vendor/aura/di/src/Aura/Di/Forge.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/Forge.php';
include $system . '/vendor/aura/di/src/Aura/Di/ConfigInterface.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/Config.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/ApcConfig.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/AnnotationInterface.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/Annotation.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/Definition.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/EmptyModule.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Bind.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Annotations/TokenParser.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/Di/Annotation.php';
include $system . '/vendor/monolog/monolog/src/Monolog/Logger.php';
include $system . '/vendor/monolog/monolog/src/Monolog/Handler/HandlerInterface.php';
include $system . '/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php';
include $system . '/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php';
include $system . '/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php';
include $system . '/vendor/guzzle/guzzle/src/Guzzle/Common/Log/LogAdapterInterface.php';
include $system . '/vendor/guzzle/guzzle/src/Guzzle/Common/Log/AbstractLogAdapter.php';
include $system . '/vendor/guzzle/guzzle/src/Guzzle/Common/Log/MonologLogAdapter.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/LoggerInterface.php';
include $system . '/src/BEAR/Framework/Inject/LogInject.php';
include $system . '/src/BEAR/Framework/Inject/Logger/Adapter.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/ResourceInterface.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Resource.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/InvokerInterface.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Invoker.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/LinkerInterface.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Linker.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/LoggerInterface.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Logger.php';
include $system . '/src/BEAR/Framework/Module/Provider/ResourceLoggerProvider.php';
include $system . '/src/BEAR/Framework/Module/Provider/ApcCacheProvider.php';
include $system . '/src/BEAR/Framework/Module/Provider/SignalProvider.php';
include $system . '/src/BEAR/Framework/Web/ResponseInterface.php';
include $system . '/src/BEAR/Framework/Web/SymfonyResponse.php';
include $system . '/src/BEAR/Framework/Exception/ExceptionHandlerInterface.php';
include $system . '/src/BEAR/Framework/Inject/LogDirInject.php';
include $system . '/src/BEAR/Framework/Exception/ExceptionHandler.php';
include $system . '/src/BEAR/Framework/Output/ConsoleInterface.php';
include $system . '/src/BEAR/Framework/Output/Console.php';
include $system . '/src/BEAR/Framework/Resource/CacheControl/Taggable.php';
include $system . '/src/BEAR/Framework/Resource/CacheControl/Etag.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/DevInvoker.php';
include $system . '/src/BEAR/Framework/Module/TemplateEngine/DevRendererModule.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Renderable.php';
include $system . '/src/BEAR/Framework/Resource/View/DevRenderer.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Advice.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Interceptor.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/MethodInterceptor.php';
include $system . '/src/BEAR/Framework/Interceptor/Logger.php';
include $system . '/src/BEAR/Framework/Annotation/Log.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Pointcut.php';
include $system . '/src/BEAR/Framework/Resource/View/HalRenderer.php';
include $system . '/src/BEAR/Framework/Module/SchemeModule.php';
include $system . '/src/BEAR/Framework/Inject/AppNameInject.php';
include $system . '/src/BEAR/Framework/Inject/InjectorInject.php';
include $system . '/src/BEAR/Framework/Module/WebContext/AuraWebModule.php';
include $system . '/src/BEAR/Framework/Module/Provider/WebContextProvider.php';
include $system . '/src/BEAR/Framework/Module/TemplateEngine/SmartyModule/SmartyModule.php';
include $system . '/src/BEAR/Framework/Inject/TmpDirInject.php';
include $system . '/src/BEAR/Framework/Inject/AppDirInject.php';
include $system . '/src/BEAR/Framework/Module/TemplateEngine/SmartyModule/SmartyProvider.php';
include $system . '/src/BEAR/Framework/Resource/View/TemplateEngineAdapter.php';
include $system . '/src/BEAR/Framework/Module/TemplateEngine/SmartyModule/SmartyAdapter.php';
include $system . '/src/BEAR/Framework/Module/Database/DoctrineDbalModule.php';
include $system . '/src/BEAR/Framework/Interceptor/DbInjector.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Object.php';
include $system . '/src/BEAR/Framework/Annotation/Db.php';
include $system . '/src/BEAR/Framework/Module/Cqrs/CacheModule.php';
include $system . '/src/BEAR/Framework/Inject/EtagInject.php';
include $system . '/src/BEAR/Framework/Interceptor/CacheLoader.php';
include $system . '/vendor/guzzle/guzzle/src/Guzzle/Common/Cache/CacheAdapterInterface.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Cache/Cache.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Cache/CacheProvider.php';
include $system . '/vendor/doctrine/common/lib/Doctrine/Common/Cache/ApcCache.php';
include $system . '/vendor/monolog/monolog/src/Monolog/Formatter/FormatterInterface.php';
include $system . '/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php';
include $system . '/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php';
include $system . '/vendor/guzzle/guzzle/src/Guzzle/Common/Cache/AbstractCacheAdapter.php';
include $system . '/vendor/guzzle/guzzle/src/Guzzle/Common/Cache/DoctrineCacheAdapter.php';
include $system . '/src/BEAR/Framework/Annotation/Cache.php';
include $system . '/src/BEAR/Framework/Interceptor/CacheUpdater.php';
include $system . '/src/BEAR/Framework/Annotation/CacheUpdate.php';
include $system . '/src/BEAR/Framework/Annotation/Time.php';
include $system . '/src/BEAR/Framework/Interceptor/TimeStamper.php';
include $system . '/src/BEAR/Framework/Annotation/Transactional.php';
include $system . '/src/BEAR/Framework/Interceptor/Transactional.php';
include $system . '/src/BEAR/Framework/Application/LoggerInterface.php';
include $system . '/src/BEAR/Framework/Application/Logger.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/BodyArrayAccess.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/AbstractObject.php';
include $system . '/src/BEAR/Framework/Resource/AbstractPage.php';
include $system . '/src/BEAR/Framework/Inject/ResourceInject.php';
include $system . '/vendor/symfony/console/Symfony/Component/Console/Output/OutputInterface.php';
include $system . '/vendor/symfony/console/Symfony/Component/Console/Output/Output.php';
include $system . '/vendor/symfony/console/Symfony/Component/Console/Output/StreamOutput.php';
include $system . '/vendor/symfony/console/Symfony/Component/Console/Output/ConsoleOutput.php';
include $system . '/vendor/guzzle/guzzle/src/Guzzle/Parser/UriTemplate/UriTemplateInterface.php';
include $system . '/vendor/guzzle/guzzle/src/Guzzle/Parser/UriTemplate/UriTemplate.php';
include $system . '/vendor/symfony/console/Symfony/Component/Console/Formatter/OutputFormatterInterface.php';
include $system . '/vendor/symfony/console/Symfony/Component/Console/Formatter/OutputFormatter.php';
include $system . '/vendor/symfony/console/Symfony/Component/Console/Formatter/OutputFormatterStyleInterface.php';
include $system . '/vendor/symfony/console/Symfony/Component/Console/Formatter/OutputFormatterStyle.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/FactoryInterface.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Factory.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Requestable.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Request.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/SchemeCollection.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Provider.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Adapter/Adapter.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/Adapter/App.php';
include $system . '/vendor/aura/signal/src/Aura/Signal/Manager.php';
include $system . '/vendor/aura/signal/src/Aura/Signal/HandlerFactory.php';
include $system . '/vendor/aura/signal/src/Aura/Signal/ResultFactory.php';
include $system . '/vendor/aura/signal/src/Aura/Signal/ResultCollection.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/SignalHandler/Handle.php';
include $system . '/vendor/bear/resource/src/BEAR/Resource/SignalHandler/Provides.php';
include $system . '/vendor/aura/signal/src/Aura/Signal/Handler.php';
include $system . '/src/BEAR/Framework/Router/Router.php';
include $system . '/src/BEAR/Framework/Resource/Link.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Weave.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Weaver.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Joinpoint.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Invocation.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/MethodInvocation.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/ReflectiveMethodInvocation.php';
include $system . '/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php';
include $system . '/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/HeaderBag.php';
include $system . '/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/ResponseHeaderBag.php';
include $system . '/src/BEAR/Framework/Application/Fireable.php';
include $system . '/src/BEAR/Framework/Application/ResourceLogIterator.php';

include $system . '/vendor/Ray/Di/src/Ray/Di/Di/Inject.php';
include $system . '/vendor/Ray/Di/src/Ray/Di/Di/Named.php';
include $system . '/vendor/Ray/Aop/src/Ray/Aop/Matched.php';
include $system . '/src/BEAR/Framework/Interceptor/DbSetterInterface.php';